export enum FineReason {
  OVERDUE = 'OVERDUE',
  LOST = 'LOST',
  DAMAGED_LIGHT = 'DAMAGED_LIGHT',
  DAMAGED_HEAVY_REPAIRABLE = 'DAMAGED_HEAVY_REPAIRABLE',
  DAMAGED_HEAVY_IRREPARABLE = 'DAMAGED_HEAVY_IRREPARABLE',
}